<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>TTGO-Osprey.SignalR</PackageId>
    <Description>SignalR client for use in Osprey networks.</Description>
    <Authors>Zia Siddique</Authors>
    <Company>TTG Options LLP</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugSymbols>true</DebugSymbols>
    <RepositoryUrl>https://github.com/TTG-Capital/ttgo-osprey</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Osprey\Osprey.csproj" />
  </ItemGroup>

</Project>
