<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PackageId>TTGO-Osprey.NLog</PackageId>
    <Description>NLog logger for Osprey.</Description>
    <Authors>Zia Siddique</Authors>
    <Company>TTG Options LLP</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugSymbols>true</DebugSymbols>
    <RepositoryUrl>https://github.com/TTG-Capital/ttgo-osprey</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Osprey\Osprey.csproj" />
  </ItemGroup>

</Project>
