<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PackageId>Osprey</PackageId>
    <Company>Sequoia Capital LLP</Company>
    <Authors>Zia Siddique</Authors>
    <Product>Osprey</Product>
    <Description>A library for decentralized communication and service discovery.</Description>
    <Tags>osprey network decentralized service mesh</Tags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="osprey.json" Pack="True">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentCommandLineParser" Version="1.4.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
