<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
    <PublishSingleFile>true</PublishSingleFile>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <IncludeNativeLibrariesInSingleFile>true</IncludeNativeLibrariesInSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="osprey.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="osprey.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentCommandLineParser" Version="1.4.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Osprey\Osprey.csproj" />
  </ItemGroup>

</Project>
